# Generated by Django 4.1.3 on 2022-11-17 13:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categories_id', models.IntegerField(default=1)),
                ('categories_type', models.CharField(max_length=100)),
                ('categories_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('status', models.CharField(default='OFFLINE', max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('employee_status', models.CharField(default='ACTIVE', max_length=100)),
                ('supervisorcode', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(default='TELLER', max_length=100)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='invoices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(default=datetime.datetime(2022, 11, 17, 15, 40, 50, 268197))),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.BigIntegerField(blank=True, null=True)),
                ('vat', models.BigIntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=100, null=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('channel', models.CharField(blank=True, max_length=100, null=True)),
                ('employeeId', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='rates',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('baseCurrency', models.CharField(max_length=10)),
                ('foreignCurrency', models.CharField(max_length=10)),
                ('rate', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='sales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('base_currency', models.CharField(blank=True, max_length=100)),
                ('channel', models.CharField(blank=True, max_length=100)),
                ('cost_price', models.BigIntegerField(null=True)),
                ('datetime', models.DateTimeField(default=datetime.datetime(2022, 11, 17, 15, 40, 50, 268197))),
                ('employeeId', models.BigIntegerField(null=True)),
                ('product', models.CharField(max_length=1000)),
                ('price', models.BigIntegerField(null=True)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('employee', models.CharField(blank=True, max_length=100)),
                ('foreign_currency', models.CharField(blank=True, max_length=100)),
                ('imei', models.CharField(blank=True, max_length=100, null=True)),
                ('invoiceId', models.BigIntegerField(null=True)),
                ('pan', models.CharField(blank=True, max_length=100, null=True)),
                ('productId', models.BigIntegerField(null=True)),
                ('quantity', models.BigIntegerField(null=True)),
                ('rate', models.BigIntegerField(null=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('rrn', models.CharField(blank=True, max_length=100, null=True)),
                ('shop_name', models.CharField(blank=True, max_length=100)),
                ('tax', models.BigIntegerField(null=True)),
                ('total', models.BigIntegerField(null=True)),
                ('status', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='suppliers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('suppliers_name', models.CharField(max_length=100)),
                ('suppliers_phone', models.CharField(max_length=100)),
                ('suppliers_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='traillogs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('user_id', models.BigIntegerField()),
                ('item', models.CharField(max_length=1000)),
                ('action', models.CharField(max_length=100)),
                ('quantity', models.BigIntegerField()),
                ('description', models.CharField(max_length=100)),
                ('createed_at', models.DateTimeField(default=datetime.datetime(2022, 11, 17, 15, 40, 50, 283826))),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('cost', models.BigIntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.BigIntegerField(blank=True, null=True)),
                ('quantity', models.BigIntegerField(blank=True, null=True)),
                ('tax', models.BigIntegerField(blank=True, null=True)),
                ('categories_id', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.categories')),
                ('suppliers_id', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.suppliers')),
            ],
        ),
        migrations.CreateModel(
            name='ordersandproducts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('barcode', models.CharField(max_length=100)),
                ('categoryId', models.BigIntegerField()),
                ('cost', models.BigIntegerField()),
                ('description', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('price', models.BigIntegerField()),
                ('quantity', models.BigIntegerField()),
                ('supplierId', models.BigIntegerField()),
                ('tax', models.BigIntegerField()),
                ('categories_id', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='apis.categories')),
                ('suppliers_id', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='apis.suppliers')),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createed_at', models.DateTimeField(default=datetime.datetime(2022, 11, 17, 15, 40, 50, 283826))),
                ('barcode', models.CharField(max_length=100)),
                ('categoryId', models.BigIntegerField()),
                ('cost', models.BigIntegerField()),
                ('description', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('price', models.BigIntegerField()),
                ('quantity', models.BigIntegerField()),
                ('supplierId', models.BigIntegerField()),
                ('tax', models.BigIntegerField()),
                ('categories_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apis.categories')),
                ('suppliers_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apis.suppliers')),
            ],
        ),
    ]
