# Generated by Django 4.1.3 on 2022-11-17 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 17, 15, 48, 55, 503725)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='createed_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 17, 15, 48, 55, 503725)),
        ),
        migrations.AlterField(
            model_name='sales',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 17, 15, 48, 55, 503725)),
        ),
        migrations.AlterField(
            model_name='traillogs',
            name='createed_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 17, 15, 48, 55, 503725)),
        ),
    ]
