# Generated by Django 4.1.3 on 2022-11-17 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_invoices_datetime_alter_orders_createed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 17, 16, 5, 41, 784259)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='createed_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 17, 16, 5, 41, 787258)),
        ),
        migrations.AlterField(
            model_name='sales',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 17, 16, 5, 41, 785262)),
        ),
        migrations.AlterField(
            model_name='traillogs',
            name='createed_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 17, 16, 5, 41, 788257)),
        ),
    ]
