# Generated by Django 4.1.3 on 2022-11-17 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_alter_invoices_datetime_alter_orders_createed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='order_level',
            field=models.BigIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 17, 16, 15, 29, 962237)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='createed_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 17, 16, 15, 29, 966234)),
        ),
        migrations.AlterField(
            model_name='sales',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 17, 16, 15, 29, 963238)),
        ),
        migrations.AlterField(
            model_name='traillogs',
            name='createed_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 17, 16, 15, 29, 967233)),
        ),
    ]
