# Generated by Django 4.1.3 on 2022-11-18 10:19

import apis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_alter_invoices_datetime_alter_orders_createed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='datetime',
            field=models.DateTimeField(default=apis.models.two_hours_hence),
        ),
        migrations.AlterField(
            model_name='orders',
            name='createed_at',
            field=models.DateTimeField(default=apis.models.two_hours_hence),
        ),
        migrations.AlterField(
            model_name='sales',
            name='datetime',
            field=models.DateTimeField(default=apis.models.two_hours_hence),
        ),
    ]
