# Generated by Django 4.1.3 on 2022-11-18 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0010_alter_invoices_datetime_alter_orders_createed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='categoryId',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='supplierId',
        ),
    ]
