# Generated by Django 4.1.3 on 2022-11-18 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0011_remove_orders_barcode_remove_orders_categoryid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='categories_id',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.categories'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='suppliers_id',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.suppliers'),
        ),
    ]
