# Generated by Django 4.1.3 on 2022-11-20 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0012_alter_orders_categories_id_alter_orders_suppliers_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='tax',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='returnedproducts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.BigIntegerField(blank=True, null=True)),
                ('categories_id', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.categories')),
                ('sales_id', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.sales')),
                ('suppliers_id', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.suppliers')),
            ],
        ),
    ]
