# Generated by Django 4.1.3 on 2022-11-21 17:20

import apis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0013_alter_orders_tax_returnedproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnedproducts',
            name='datetime',
            field=models.DateTimeField(default=apis.models.two_hours_hence),
        ),
    ]
