# Generated by Django 4.1.3 on 2022-12-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0014_returnedproducts_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
