# Generated by Django 4.1.3 on 2024-01-04 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0015_alter_employees_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poisonous',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('poisonous_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apis.poisonous')),
            ],
            bases=('apis.poisonous',),
        ),
    ]
